config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  scope "(:locale)", :locale => /en|fr/ do
    root to: 'pages#index'
    get "pages/index"
  end

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  resources :users
  resources :posts
  resources :comments

  match '*a', :to => 'errors#routing', via: :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :content, presence: true
  validates :content, length: { maximum: 255 }
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, :content, presence: true
  validates :title, length: { maximum: 255 }

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  
  has_attached_file :photo
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :username, :email, presence: true, uniqueness: true
  validates :username, length: { maximum: 150 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
  before_action :set_locale
 
  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    Rails.application.routes.default_url_options[:locale]= I18n.locale 
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_comment, only: [:edit, :update, :show, :delete]

  def index
    @comments = Comment.all
  end

  def show
      @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
		@comment = Comment.new(comment_params)
    if @comment.save
			flash[:message] = "Comment was successfully created."
    end
		redirect_back(fallback_location: root_path)
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    flash[:info] = "Comment deleted" 
    
		redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    if current_user
      params.require(:comment).permit!
    end
  end

  def find_comment
    begin
      @comment = Comment.find(params[:id])
    rescue => exception
      render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    end
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def routing
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @posts = Post.last(6).reverse
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :find_post, only: [:edit, :update, :show, :delete]

  def index
   @posts = Post.order('created_at DESC').paginate(:page => params[:page], per_page: 6)
  end

  def show
    @currentUser = current_user.id
      @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
		@post = Post.new(post_params)
      	if @post.save
			flash[:message] = "Post was successfully created."
			redirect_to posts_path
      	else
			render action: 'new'
		end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    flash[:info] = "Post deleted" 
    
    redirect_to root_url
  end

  private

  def post_params
    if current_user
      params.require(:post).permit!
    end
  end

  def find_post
    begin
      @post = Post.find(params[:id])
    rescue => exception
      render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    end
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit( :username, 
                                  :email, 
                                  :password, 
                                  :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit( :username, 
                                  :email, 
                                  :password, 
                                  :password_confirmation, 
                                  :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:edit, :update, :show, :delete]

  def index
    @users = User.order('created_at DESC').paginate(:page => params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
   # @posts = @user.posts
   @posts = @user.posts.order('created_at DESC').paginate(:page => params[:page], per_page: 6)
  end

  def new
    @user = User.new
  end

  def create

    @user = User.create(params[:user].permit!)

    redirect_to user_path(@user.id) if @user.persisted?

  end

  def update
    
  end

  def edit
    @user = User.find(1)
  end

  def destroy
    @user = User.find(1)
  end

  private

  def find_user
    begin
      @user = User.find(params[:id])
    rescue => exception
      render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_url(email, size)
    gravatar = Digest::MD5::hexdigest(email).downcase
    url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end
  
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<h2><%= t("add_comment") %></h2>
<%= form_for [@comment, Comment.new] do |f| %>
  <%= f.text_area :content, placeholder: true, class: 'comment_content' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.submit t("send") %>

<% end %>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="lang">
  <% if I18n.locale == I18n.default_locale %>
    <%= link_to_unless I18n.locale == :en, "EN", locale: :en%>
    <% else %>
    <%= link_to_unless I18n.locale == :de, "FR", locale: :fr %>
  <% end %>
  </div>
  <div class="logo">
    <svg version="1.1" x="0px" y="0px" viewBox="0 0 160 160" xml:space="preserve"><path d="M112.2,43c-3.8,1.7-7.3,3.1-10.6,4.8c-14.7,7.3-29.2,14.8-43.9,22c-7.8,3.8-15.6,7.3-24.2,8.9c-3.9,0.7-7.8,0.7-11.6-0.5	c-5.3-1.6-9.3-7.3-9.6-13.9C11.8,50.9,17.7,40.4,28,32.5c25.2-19.3,61-15.7,82.2,8C110.8,41.2,111.3,41.9,112.2,43z"/><path d="M78.4,138.8c3.2-2.2,6.6-4.1,9.6-6.6c4.9-4,8.4-8.9,9.7-15.2c2.2-10.5-5.1-20.1-15.8-20.7c-8.9-0.5-17.1,2.1-25.2,5.3	c-17.6,6.8-35.2,13.5-52.8,20.3c-0.7,0.3-1.5,0.3-2.2,0.4c-0.1-0.3-0.2-0.5-0.3-0.8c43.8-28.1,87.6-56.3,131.4-84.4	c0.2,0.1,0.4,0.3,0.6,0.4c-0.4,0.8-0.6,1.7-1.2,2.3c-3.5,4.3-7.1,8.6-10.7,12.8c-1.2,1.4-1.5,2.5-0.8,4.2	c13.8,32.1-2.6,69.1-35.6,80.5c-2.2,0.7-4.4,1.3-6.5,2C78.5,139.2,78.4,139,78.4,138.8z"/><path d="M144.5,44c-2.8-7.3-7-13.8-12.7-19.3c0.1-0.2,0.3-0.5,0.4-0.7c2.4,0.4,4.8,0.7,7.1,1.3c2,0.6,3.6-0.1,5.4-0.8	c3.2-1.4,6.6-2.3,9.9-3.2c0.9-0.3,1.9,0,3.5,0c-0.9,1.7-1.3,3.1-2.2,4.1c-1.8,2.2-3.6,4.7-5.9,6.4c-2.5,1.8-3.3,4.2-3.8,6.9	c-0.3,1.8-0.8,3.5-1.2,5.3C145,43.9,144.7,44,144.5,44z"/></svg>  
  </div>
  <nav class="nav">
    <ul>
      <li><%= link_to t('home'), root_path %></li>
      <% if !current_user %>
      <li><%= link_to t('register'), new_user_registration_path %></li>
      <li><%= link_to t('login'), login_path %></li>
      <% else %>
      <li><%= link_to t('new_article'), new_post_path, class: 'nav__new_item' %></li>
      <li><%= link_to t('articles'), posts_path %></li>
      <li><%= link_to t('users'), users_path %></li>
      <li><%= link_to t('logout'), destroy_user_session_path, method: :delete %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width,initial-scale=1, viewport-fit=cover">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700|Open+Sans:400,600" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container">
  <h1><%= t('home') %></h1>
  <div class="articles__container">
    <%= render @posts %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="article">
  <div class="article__background">
    <%= image_tag post.photo.url %>
  </div>
  <h3 class="article__title"><%= truncate(post.title, :length => 20) %></h3>
  <p class="article__description"><%= truncate(post.content, :length => 65) %></p>
  <%= link_to t('read'), post_path(post.id), class: "article__link" %>
</div>

app/views/posts/index.html.erb
<main class="container">
  <h1><%= t("articles") %></h1>

  <div class="articles__container">
    <%= render @posts %>
  </div>  
  <%= will_paginate @posts %>
</main>

app/views/posts/new.html.erb
<main class="container container-new">
  <h1><%= t("add_article") %></h1>
  <p class="add_subtitle">
  <%= t("add_article_subtitle") %>
  </p>
  <%= form_for @post, html: { multipart: true } do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: true %>
    <%= f.label :content %>
    <%= f.text_area :content, placeholder: true %>
    <%= f.label :photo =%>
    <%= f.file_field :photo %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit t('send')%>
  <% end %>
</main>

app/views/posts/show.html.erb
<div class="article__background">
  <%= image_tag @post.photo.url %>
</div>
  <main class="container container-article">
  <h1><%= @post.title %></h1>
  <p><%= @post.content %></p>
  <p><%= t("published_by") %> <%= @post.user.username %></p>
  <% unless @post.comments.blank? %>
    <h2><%= t("comments") %></h2>
    <% @post.comments.each do |comment|  %>
      <div class="comment">
        <strong><%= link_to comment.user.username, {controller: "users", action: "show", id: comment.user.id} %></strong>
        <p><%= comment.content %></p>
      <% if current_user.id === comment.user.id || @post.user.id === current_user.id %>
        <%= link_to t("delete_comment"), comment_path(comment.id), method: :delete, data: { confirm: t('confirm_delete_comment') }, class: 'comment_delete' %>
      <% end %>
      </div>      
    <% end %>
  <% else %>
    <p><%= t("no_comments") %></p>
  <% end %>
  <%= render partial: 'comments/form', locals: { comment: @comment } %>
  <% if current_user.id === @post.user.id %>
        <%= link_to t('delete_post'), post_path(@post.id), method: :delete, data: { confirm: t('confirm_delete_post') } %>
  <% end %>
</main>

app/views/users/_user.html.erb
<div class="user">
  <div class="user__avatar">
  
  <%= image_tag gravatar_url(user.email, 140), alt: "" %>
  </div>
  <div class="user__about">
    <div class="about__name"><%= user.username %></div>
    <p class="about__register"><%= time_ago_in_words(user.created_at) %></p>
    <%= link_to t('see'), user_path(user.id), class: "about__link" %>  
  </div>
</div>

app/views/users/index.html.erb
<main class="container">
  <h1><%= t("users") %></h1>
  <div class="users__container">
    <%= render @users %>
  </div>
  <%= will_paginate @users %>
</main>

app/views/users/show.html.erb
<main class="container">
  <h1><%= @user.username %></h1>
  <p><%= @user.email %></p>
  <p><%= t("register_at") %> <%= @user.created_at %></p>
  <% if @posts.count > 0 %>
    <div class="articles__container">
      <%= render @posts %>
    </div>
    <%= will_paginate @posts %>
    <% else %>
    <p><%= t('no_articles') %></p>
  <% end %>
</main>